### ISSUE TITLE
setParseComments(true) causes YAML parser to fail incorrectly

### ISSUE THREAD

**Issue by avosirenfal** [krzema12/snakeyaml-engine-kmp#478]
When `setParseComments(true)` is set on `LoadSettings` some valid YAML fails to parse, trigger seems to be a block comment that follows a custom tag. Library version `it.krzeminski:snakeyaml-engine-kmp:3.1.1`

Minimal reproduction:

```kotlin
import it.krzeminski.snakeyaml.engine.kmp.api.LoadSettings
import it.krzeminski.snakeyaml.engine.kmp.api.lowlevel.Compose

fun testYaml(withComments: Boolean) {
	val contents = """
- lowerBound: !type:AlarmThresholdSetting
    # Actual low pressure damage threshold is at 20 kPa, but below ~85 kPa you can't breathe due to lack of oxygen.
    threshold: 85
	""".trimIndent()

	val settings = LoadSettings.builder()
		.setParseComments(withComments)
		.build()
	val composer = Compose(settings)
	composer.compose(contents)!!
}

fun main() {
	testYaml(false)
	println("without comments: pass")
	testYaml(true) // crashes here
	println("with comments: pass")
}
```

Stack trace:

```
Exception in thread "main" it.krzeminski.snakeyaml.engine.kmp.exceptions.ParserException: while parsing a block mapping
 in reader, line 1, column 3:
    - lowerBound: !type:AlarmThreshold ... 
      ^
expected <block end>, but found '<block mapping start>'
 in reader, line 3, column 5:
        threshold: 85
        ^

	at it.krzeminski.snakeyaml.engine.kmp.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.kt:638)
	at it.krzeminski.snakeyaml.engine.kmp.parser.ParserImpl.produce(ParserImpl.kt:151)
	at it.krzeminski.snakeyaml.engine.kmp.parser.ParserImpl.peekEvent(ParserImpl.kt:128)
	at it.krzeminski.snakeyaml.engine.kmp.comments.EventQueue$2.invoke(CommentEventsCollector.kt:150)
	at it.krzeminski.snakeyaml.engine.kmp.comments.EventQueue$2.invoke(CommentEventsCollector.kt:150)
	at it.krzeminski.snakeyaml.engine.kmp.comments.EventQueue.peek(CommentEventsCollector.kt:159)
	at it.krzeminski.snakeyaml.engine.kmp.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.kt:101)
	at it.krzeminski.snakeyaml.engine.kmp.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.kt:81)
	at it.krzeminski.snakeyaml.engine.kmp.composer.Composer.composeMappingNode(Composer.kt:299)
	at it.krzeminski.snakeyaml.engine.kmp.composer.Composer.composeNode(Composer.kt:165)
	at it.krzeminski.snakeyaml.engine.kmp.composer.Composer.composeSequenceNode(Composer.kt:252)
	at it.krzeminski.snakeyaml.engine.kmp.composer.Composer.composeNode(Composer.kt:163)
	at it.krzeminski.snakeyaml.engine.kmp.composer.Composer.next(Composer.kt:119)
	at it.krzeminski.snakeyaml.engine.kmp.composer.Composer.getSingleNode(Composer.kt:76)
	at it.krzeminski.snakeyaml.engine.kmp.api.lowlevel.ComposeCommon.compose(ComposeCommon.kt:31)
	at it.krzeminski.snakeyaml.engine.kmp.api.lowlevel.ComposeCommon.compose(ComposeCommon.kt:34)
	at it.krzeminski.snakeyaml.engine.kmp.api.lowlevel.Compose.compose(Compose.kt:30)
	at MainKt.testYaml(main.kt:15)
	at MainKt.main(main.kt:21)
	at MainKt.main(main.kt)
```

**Comment by krzema12** [comment]
A fix for this issue was made in the upstream project. Here's a task to port these changes to snakeyaml-engine-kmp: https://github.com/krzema12/snakeyaml-engine-kmp/issues/571. Keeping this one open for visibility.

**Comment by krzema12** [comment]
The fix has been released in https://github.com/krzema12/snakeyaml-engine-kmp/releases/tag/v3.2.1.

**Comment by avosirenfal** [comment]
Unless I'm misunderstanding [upstream ticket](https://bitbucket.org/snakeyaml/snakeyaml-engine/issues/68/comments-are-not-parsed-correctly-when) Andrey Somov said-

> I will not try to fix it in the nearest future.
> Any contribution is welcome.
> 
> A test was added to clarify the issue: [...]

It does seem like [here](https://github.com/krzema12/snakeyaml-engine-kmp/pull/577#discussion_r2377061247) that the new tests do still throw for you in Snakeyaml-KMP (as we'd expect, since I guess they also throw for upstream).

So this should, perhaps, be closed as wontfix instead.

**Comment by krzema12** [comment]
@avosirenfal you're right! I got confused by a fix in production code made here: https://github.com/krzema12/snakeyaml-engine-kmp/pull/577/files#diff-f89401806cea512fac410e4cca4c0ffbb6049310844f32ae3ff6b094d1f370d3. I double-checked it, and it just fixes parsing a comment after a scalar where the test includes `setParseComments(true)`.

Let me:
1. Resolve this bug as wontfix.
2. Extend `CommentAfterAliasTest` to assert that when `setParseComments` is set to `true`, parsing fails.
